filecopy:
  campaigns:
    - name: "scalinea"
      src: 
        - "../git/conservatorium/300 DnD/30-39 Campaigns/32 SumonHo/300.32.01 SessionNotes"
      dst: 
        - "./docs/Campaigns/Scalinea/Session Notes"
    - name: "dotmm"
      src: 
        - "../git/conservatorium/300 DnD/30-39 Campaigns/31 DotMM/300.31.01 SessionNotes"
      dst: 
        - "./docs/Campaigns/DotMM/Session Notes"
  compendiums:
    - name: 'People'
      src: 
        - "../git/conservatorium/300 DnD/40-49 Compendium/40 People/300.40.01 Characters"
        - "../git/conservatorium/300 DnD/40-49 Compendium/40 People/300.40.02 NPCs"
      dst: 
        - "./docs/Compendium/People/Characters"
        - "./docs/Compendium/People/NPCs"
    - name: 'History'
      src: 
        - "../git/conservatorium/300 DnD/40-49 Compendium/41 History"
      dst: 
        - "./docs/Compendium/History"
    - name: 'Geography'
      src:
        - "../git/conservatorium/300 DnD/40-49 Compendium/42 Geography/300.42.01 Regions"
        - "../git/conservatorium/300 DnD/40-49 Compendium/42 Geography/300.42.02 Settlements"
        - "../git/conservatorium/300 DnD/40-49 Compendium/42 Geography/300.42.03 Natural Locations"
        - "../git/conservatorium/300 DnD/40-49 Compendium/42 Geography/300.42.04 Services"
        - "../git/conservatorium/300 DnD/40-49 Compendium/42 Geography"
      dst:
        - "./docs/Compendium/Geography/Regions"
        - "./docs/Compendium/Geography/Settlements"
        - "./docs/Compendium/Geography/Natural Locations"
        - "./docs/Compendium/Geography/Services"
        - "./docs/Compendium/Geography"
    - name: 'Religion'
      src:
        - "../git/conservatorium/300 DnD/40-49 Compendium/43 Religion"
      dst:
        - "./docs/Compendium/Religion"
    - name: 'Organizations'
      src:
        - "../git/conservatorium/300 DnD/40-49 Compendium/44 Organizations"
      dst:
        - "./docs/Compendium/Factions"
    - name: 'Magic'
      src:
        - "../git/conservatorium/300 DnD/40-49 Compendium/45 Magic"
      dst:
        - "./docs/Compendium/Magic"
    - name: 'Bestiary'
      src:
        - "../git/conservatorium/300 DnD/40-49 Compendium/46 Bestiary"
      dst:
        - "./docs/Compendium/Bestiary"