site_name: session-notes
site_url: https://jpbruckler.github.io/session-notes

theme:
    name: 'material'
    features:
    - navigation.instant

    palette:


    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - admonition 
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.emoji
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
#  - pymdownx.tilde
#  - toc:
#      permalink: true
#  - pymdownx.arithmatex:
#      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - roamlinks 
  - mermaid2
  - tags:
      tags_file: tags.md

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
