site_name: session-notes

theme:
    name: 'material'
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.arithmatex:
      generic: true
<<<<<<< HEAD
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.emoji
  - pymdownx.tasklist
=======
  # - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
>>>>>>> a40d65293465f49740ab8d223efb2b469e6ccf60
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 
  - mermaid2
  - tags:
      tags_file: tags.md

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
